const Amarok  = require('../lib/events');
const {WAConnection, MessageOptions, MessageType, Mimetype, Presence} = require('@adiwajshing/baileys');
const fs = require('fs');
const axios = require('axios');

Amarok.addCMD(
        {      pattern: 'glue ?(.*)',
               isOwner: false,
               desc: 'maker logo with it',
               type: 'user',
     },
     async(conn,match) => {
     match = match[1] 
     if (!match) return await conn.reply('_Need query_');
     var webimage = await axios.get(`https://zenzapi.xyz/api/textpro/gluetext?text=${match[1]}&apikey=b91fbfa191`,
     await conn.sendMessage(conn.chatld, Buffer.from(webimage.data), MessageType.image, {mimetype: Mimetype.jpg, caption: '*generated by amarok*'})
}));
